require "user.settings"
require "user.keymaps"
require "user.autocomands"
require "plugins.plugins"
require "colors.color-configs"
require "colors.colorscheme"
require "plugins.settings.impatient"
require "plugins.settings.alpha"
require "plugins.settings.autopairs"
require "plugins.settings.bufferline"
require "plugins.settings.cmp"
require "plugins.settings.colorizer"
require "plugins.settings.comment"
require "plugins.settings.floaterm"
require "plugins.settings.gitsigns"
require "plugins.settings.indentline"
require "plugins.settings.eviline"
-- require "plugins.settings.ideline"
-- require "plugins.settings.lualine"
require "plugins.settings.lazygit"
require "plugins.settings.nvim-tree"
require "plugins.settings.project"
require "plugins.settings.telescope"
require "plugins.settings.treesitter"
require "plugins.settings.whichkey"
require "plugins.settings.lsp"
