-- Put your colorscheme config files down below
require "colors.color-configs.catppuccin"
require "colors.color-configs.dracula"
require "colors.color-configs.gruvbaby"
require "colors.color-configs.gruvbox"
require "colors.color-configs.kanagawa"
require "colors.color-configs.nord"
require "colors.color-configs.onedark"
require "colors.color-configs.onenord"
require "colors.color-configs.tokyonight"
