-- Comment to disable plugins
-- require "plugins.settings.alpha"
require "plugins.settings.autopairs"
require "plugins.settings.bufferline"
require "plugins.settings.cmp"
require "plugins.settings.colorizer"
require "plugins.settings.comment"
require "plugins.settings.floaterm"
require "plugins.settings.functions"
require "plugins.settings.gitsigns"
require "plugins.settings.gps"
require "plugins.settings.impatient"
require "plugins.settings.indentline"
require "plugins.settings.lazygit"
require "plugins.settings.nvim-tree"
require "plugins.settings.project"
require "plugins.settings.statusline"
require "plugins.settings.telescope"
require "plugins.settings.treesitter"
require "plugins.settings.whichkey"
require "plugins.settings.winbar"
require "plugins.settings.lsp"
